// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.501
package stream

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func HlsLoader(streamId string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_HlsLoader_d4c0`,
		Function: `function __templ_HlsLoader_d4c0(streamId){if (Hls.isSupported()) {
        var video = document.getElementById('stream');
        var hls = new Hls();
        hls.on(Hls.Events.MEDIA_ATTACHED, function () {
        console.log('video and hls.js are now bound together !');
        });
        hls.on(Hls.Events.MANIFEST_PARSED, function (event, data) {
        console.log(
            'manifest loaded, found ' + data.levels.length + ' quality level',
        );
        });
        hls.loadSource(` + "`" + `/video/${streamId}/${streamId}-master.m3u8` + "`" + `);
        // bind them together
        hls.attachMedia(video);
    } else {
        alert("HLS not suppoted, use compatible browser as Google Chrome, Safari, Firefox, etc!")
    }}`,
		Call:       templ.SafeScript(`__templ_HlsLoader_d4c0`, streamId),
		CallInline: templ.SafeScriptInline(`__templ_HlsLoader_d4c0`, streamId),
	}
}

func StreamView(userLanguage []string, streamId string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script src=\"/assets/hls\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := ``
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script><video controls autoplay id=\"stream\"></video>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = HlsLoader(streamId).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
